# Generated by Django 3.1.7 on 2021-11-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='second',
            field=models.BooleanField(default=False),
        ),
    ]
